name: Docker image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: Build and publish Docker image to Docker Hub and GitHub Containers Repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Remove "_Docker" suffix from GitHub repository name to use it as image name
      uses: mad9000/actions-find-and-replace-string@3
      id: docker_image_name
      with:
        source: ${{ github.repository }}
        find: '_Docker'
        replace: ''
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ steps.docker_image_name.outputs.value }}
          ghcr.io/${{ steps.docker_image_name.outputs.value }}
        tags: type=raw,value=latest
        labels: |
          org.opencontainers.image.title=iDRAC Fan Controller
          org.opencontainers.image.description=Python-based Dell iDRAC fan controller
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and publish Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
